blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('posts/', views.post_list, name="post_list"),
    path('posts/<slug:category_slug>/', views.post_list, name="post_list_by_category"),
    path('posts/d/<slug:post_slug>/', views.post_detail, name="post_detail"),
]

pyblog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views
# import xadmin
# xadmin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls", namespace="blog")),
    path('register/', user_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('profil/', user_views.profil, name="profil"),
    path('profil/update', user_views.profil_update, name="profil-update")

    # url(r'xadmin/', include(xadmin.site.urls)),
    # url(r'^xadmin/', include(xadmin.site.urls), name='xadmin'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'categories'
        ordering = ['-created_date']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:post_list_by_category', args=[self.slug])

class Post(models.Model):
    category = models.ForeignKey(Category, related_name='posts', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'product'
        ordering = ['-created_date']
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.

class Profil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="profil_pics", default="profil.png")
    information = models.TextField()

    def __str__(self):
        return f'{self.user.username} Profil'

    def save(self):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            img_size = (300, 300)
            img.thumbnail(img_size)
            img.save(self.image.path)

blog/forms.py
from django import forms
from .models import Category, Post

class CategoryAdminForm(forms.ModelForm):
    class Meta:
        model = Category
        exclude = ('created_date', 'updated_date')

class PostAdminForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('created_date', 'updated_date')

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profil


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfilUpdateForm(forms.ModelForm):

    class Meta:
        model = Profil
        fields = ['image', 'information']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Post
from django.core.paginator import Paginator
from users.models import Profil

# Create your views here.
def home(request):
    posts = Post.objects.all()[:4]
    context = {'posts': posts}
    return render(request, "blog/index.html", context)

def about(request):
    profils = Profil.objects.all()
    context = {'profils': profils}
    return render(request, "blog/about.html", context)


def post_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    posts = Post.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        posts = Post.objects.filter(category=category)

    paginator = Paginator(posts, 3)
    page = request.GET.get('page')

    posts = paginator.get_page(page)

    context = {'posts': posts, 'categories': categories, 'category': category}
    return render(request, "blog/post_list.html", context)

def post_detail(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug)
    categories = Category.objects.all()
    context = {'post': post, 'categories': categories,}
    return render(request, "blog/post_detail.html", context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfilUpdateForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Votre compte a ete cree avec success {username}')
            return redirect('profil')
    else:
        form = UserRegisterForm()
    context = {'form': form}
    return render(request, "users/register.html", context)

@login_required
def profil(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST)
        p_form = ProfilUpdateForm(request.POST)
    else:
        u_form = UserUpdateForm()
        p_form = ProfilUpdateForm()

    context = {'u_form': u_form, 'p_form': p_form}
    return render(request, "users/profil.html", context)


@login_required
def profil_update(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfilUpdateForm(request.POST, request.FILES, instance=request.user.profil)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Votre compte a ete modifie avec success')
            return redirect('profil')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfilUpdateForm(instance=request.user.profil)

    context = {'u_form': u_form, 'p_form': p_form}
    return render(request, "users/profil_update.html", context)

blog/templates/blog/about.html
{% extends "layout/base.html" %}

{% block content %}
    <section class="work bg-secondary text-white">
        <div class="row">
            <div class="container text-center py-5">
                <h2>We Work For You</h2>
                <h4>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem velit aperiam, unde aliquid at similique!</h4>
                <hr>
                <a href="{% url 'blog:post_list' %}" class="btn btn-success text-white btn-lg">View Pur Posts</a>
            </div>
        </div>
    </section>
    <section class="py-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="title text-center">
                        <h2>Our Team</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for profil in profils %}
                <div class="col-md-4 text-center mt-5">
                <img src="{{ profil.image.url }}" class="img-responsive rounded-circle" height="200px" width="200px">
                    <hr>
                    <h6 class="mt-2"><a href="{% url 'profil' %}">{{ profil.user.first_name }} {{ profil.user.last_name }}</a></h6>
                    <h6 class="mt-2">{{ profil.user.email }}</h6>
                    <p>{{ profil.information|truncatechars:200 }}</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock content %}

blog/templates/blog/index.html
{% extends "layout/base.html" %}

{% block content %}
<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container text-center">
      <h1 class="display-3">Hello, world!</h1>
      <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
      <p><a class="btn btn-success btn-lg" href="{% url 'blog:post_list' %}" role="button">All Posts &raquo;</a></p>
    </div>
  </div>

</main>
<section>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6 text-center mb-3">
        <h2>Last Posts</h2>
      </div>
    </div>
  </div>
</section>
<section>
  <div class="container">
    <div class="row">
      {% for post in posts %}
      <div class="col-lg-6">
        <div class="card mb-2">
          <div class="card-body">
            <div class="media">
              <img src="{{ post.author.profil.image.url }}" width="60" height="60" class="mr-3 rounded-circle">
              <div class="media-body">
                <h6><a href="{% url 'blog:post_detail' post.slug %}">{{ post.title }}</a></h6>
                <p>{{ post.content|truncatechars:160 }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<section id="services" class="mt-4">
  <div class="container">
    <div class="row">
      <div class="col-md-4 text-center">
        <i class="fas fa-phone-volume fa-4x"></i>
        <hr>
        <h3>Service Free</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, debitis nam! Repudiandae, provident iste consequatur hic dignissimos ratione ea quae.</p>
      </div>
      <div class="col-md-4 text-center">
        <i class="fas fa-users fa-4x"></i>
        <hr>
        <h3>Professional Team</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, debitis nam! Repudiandae, provident iste consequatur hic dignissimos ratione ea quae.</p>
      </div>
      <div class="col-md-4 text-center">
        <i class="far fa-comments fa-4x"></i>
        <hr>
        <h3>Community Service</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, debitis nam! Repudiandae, provident iste consequatur hic dignissimos ratione ea quae.</p>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "layout/base.html" %}

{% block content %}
<section class="my-4">
    <div class="container">
        <div class="row">

            <div class="col-lg-9">
                <div class="card my-2">
                    <div class="card-body">
                        <small class="text-muted">posté le {{ post.created_date|date:"d F Y" }}</small>
                        <hr>
                        <h6><a href="{% url 'blog:post_detail' post.slug %}">{{ post.title }}</a></h6>
                        <p>{{ post.content }}</p>
                        <h6>Catégorie :<a href="{% url 'blog:post_list' %}"> {{ post.category }}</a></h6>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="list-group">
                  <a href="{% url 'blog:post_list' %}" class="list-group-item list-group-item-action bg-color-list-group"> Catégories</a>

                    {% if category %}
                    <a href="{% url 'blog:post_list_by_category' category.slug %}" class="list-group-item list-group-item-action">{{ category }}</a>
                    {% endif %}

                    {% for category in categories %}
                    <a href="{% url 'blog:post_list_by_category' category.slug %}" class="list-group-item list-group-item-action">{{ category }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

blog/templates/blog/post_list.html
{% extends "layout/base.html" %}

{% block content %}
<section class="my-4">
    <div class="container">
        <div class="row">

            <div class="col-lg-9">
                {% for post in posts %}
                    <div class="card mb-2">
                        <div class="card-body">
                            <div class="media">
                                <div class="media-body">
                                    <a href="#" class="mt-0">{{ post.author }}</a>
                                    <small class="text-muted">posté le {{ post.created_date|date:"d F Y" }}</small>
                                    <hr>
                                    <h6><a href="{% url 'blog:post_detail' post.slug %}">{{ post.title }}</a></h6>
                                    <p>{{ post.content|linebreaks }}</p>
                                    <h6>Catégorie :<a href="{% url 'blog:post_list_by_category' post.category.slug %}"> {{ post.category }}</a></h6>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <div class="col-lg-3">
                <div class="list-group">
                  <a href="{% url 'blog:post_list' %}" class="list-group-item list-group-item-action bg-color-list-group"> Catégories</a>
                    {% for category in categories %}
                    <a href="{% url 'blog:post_list_by_category' category.slug %}" class="list-group-item list-group-item-action">{{ category }}</a>
                    {% endfor %}
                </div>
            </div>

        </div>

        <div class="pagination">
            <span class="step-links">
                {% if posts.has_previous %}
                    <a href="?page=1" class="btn btn-outline-info">&laquo; first</a>
                    <a href="?page={{ posts.previous_page_number }}" class="btn btn-outline-info">previous</a>
                {% endif %}

                {% for num in posts.paginator.page_range %}
                    {% if contacts.number == num %}
                    <a href="?page={{ num }}" class="btn btn-outline-info">{{ num }}</a>
                    {% elif num > posts.number|add:'-2' and num < posts.number|add:'2' %}
                    <a href="?page={{ num }}" class="btn btn-outline-info">{{ num }}</a>
                    {% endif %}
                {% endfor %}

                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}" class="btn btn-outline-info">next</a>
                    <a href="?page={{ posts.paginator.num_pages }}" class="btn btn-outline-info">last &raquo;</a>
                {% endif %}
            </span>
        </div>

    </div>
</section>

{% endblock content %}

templates/layout/base.html
{% load static %}
<!doctype html>
<html lang="fr">
  <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css">
      <link rel="stylesheet" href="{% static 'css/style.css' %}">

      {% if title %}
      <title>Django Blog - {{ title }}</title>
      {% else %}
      <title>Django Blog</title>
      {% endif %}
  </head>
  <body>

    {% include 'partials/header.html' %}

    {% block content %}

    {% endblock content %}

    {% include 'partials/footer.html' %}

  <script src="{% static 'jquery.min.js' %}"></script>
  <script src="{% static 'popper.min.js' %}"></script>
  <script src="{% static 'bootstrap.min.js' %}"></script>

  </body>
</html>

templates/partials/footer.html
<footer>
    <div class="container mt-4 text-center">
    <p>&copy; Django Blog | SD 2019</p>
    </div>
</footer>

templates/partials/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-color">
  <div class="container">
    <a class="navbar-brand" href="/">Django-Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample07">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_list' %}">Posts <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:about' %}">About</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{% url 'profil' %}">Profil</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Deconnexion</a></li>
        {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Inscription</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Connexion</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/partials/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

users/templates/partials/nav_profil.html
<section class="mt-4">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <ul class="list-group list-group-horizontal-xl">
                  <li class="list-group-item"><a href="{% url 'profil' %}">Tableau de bord</a></li>
                  <li class="list-group-item"><a href="{% url 'profil-update' %}">Mon Compte</a></li>
                  <li class="list-group-item"><a href="#">Mes Posts</a></li>
                  <li class="list-group-item"><a href="#">Publier une annonce</a></li>
                </ul>
            </div>
        </div>
    </div>
</section>

users/templates/users/login.html
{% extends "layout/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<section class="my-4">
    <div class="container my-5">
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-9">
                {% include 'partials/messages.html' %}
                <div class="card">
                    <div class="card-header">
                        <h3>Connexion</h3>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form|crispy }}
                            </div>
                            <div class="form-group">
                                <button class="btn btn-outline-info" type="submit">Connexion</button>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Vous n'avez pas de compte ? <a href="#"></a>Inscription</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

users/templates/users/profil.html
{% extends "layout/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
{% include 'partials/nav_profil.html' %}
<section class="my-4">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="card">
                    <img src="{{ user.profil.image.url }}"  class="card-img-top img-responsive">
                    <div class="card-body text-center">
                        <h6>{{ user.first_name }} {{ user.last_name }}</h6>
                        <h6>{{ user.email }}</h6>
                        <h6>Création : {{ user.date_joined|date:"d F Y" }}</h6>
                        <h6>Dernière connexion</h6>
                        <small>Date : {{ user.last_login|date:"d F Y" }}</small><br>
                        <small>Heure : {{ user.last_login|time:"H:i" }}</small>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="card">
                    <div class="card-body">
                        <h6>{{ user.username }}</h6>
                        <p>{{ user.profil.information|linebreaks }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

users/templates/users/profil_update.html
{% extends "layout/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

{% include 'partials/nav_profil.html' %}

<section class="my-4">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="card">
                    <img src="{{ user.profil.image.url }}"  class="card-img-top img-responsive">
                    <div class="card-body text-center">
                        <h6>{{ user.first_name }} {{ user.last_name }}</h6>
                        <h6>{{ user.email }}</h6>
                        <span>Création : {{ user.date_joined }}</span>
                        <span>Dernière connexion : {{ user.last_login }}</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                {% include 'partials/messages.html' %}
                <div class="card">
                    <div class="card-header">
                        <h3>Modifier Mon Profil</h3>
                    </div>
                    <div class="card-body">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ u_form|crispy }}
                                {{ p_form|crispy }}
                            </div>
                            <div class="form-group">
                                <button class="btn btn-outline-info" type="submit">Inscription</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

users/templates/users/register.html
{% extends "layout/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<section class="my-4">
    <div class="container">
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-9">
                {% include 'partials/messages.html' %}
                <div class="card">
                    <div class="card-header">
                        <h3>Inscription</h3>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form|crispy }}
                            </div>
                            <div class="form-group">
                                <button class="btn btn-outline-info" type="submit">Inscription</button>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Avez-vous un compte ? <a href="#"></a>Connexion</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}